server:
  port: 99
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Never
    url: jdbc:mysql://localhost:3306/hospital
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
  mail: 
        host: smtp.gmail.com
        port: 587
        username: myact5050@gmail.com
        password: Myact5041
        properties:
         mail:
          smtp:
           starttls:
            enable: true
    